#!/bin/sh
# Start/stop a transparent squid proxy in a container. System podman containers will
# automatically use this to route plain http traffic through the cache, and thus
# greatly speed up the kickstart tests.
#
# This does NOT work with user podman containers, as they don't use a bridge, but slirp.
# Transparent content caching does NOT work with https in principle.
#
# If $HTTP_PROXY is set, squid chains to it instead of fetching directly, so this
# also works on hosts whose only egress is through a proxy.
#
# Call this with "clean" to  drop the persistent squid cache.

set -eu

MYDIR=$(dirname $(realpath "$0"))
CRUN=${CRUN:-$(which podman docker 2>/dev/null | head -n1)}

# Generated, not checked in: it depends on the environment squid runs in.
PARENT_CONF=/run/kstest-squid-parent.conf

is_running() {
    [ -n "$($CRUN ps -q -f 'name=^squid$')" ]
}

# Where hosts that only permit proxied egress (such as the OpenShift runners)
# advertise their proxy. Both spellings are in common use.
proxy_url() {
    echo "${HTTP_PROXY:-${http_proxy:-}}"
}

# Chain squid to the host's proxy when there is one. Without this, squid tries
# to reach mirrors directly; where direct egress is blocked those connections
# time out rather than being refused, so tests hang with no error instead of
# failing. Nothing is written when the host has no proxy, which keeps the
# normal unrestricted case exactly as it was.
write_parent_conf() {
    url=$(proxy_url)
    # http://[user:pass@]host[:port][/] -> host, port
    hostport=${url#*://}
    hostport=${hostport%%/*}
    # Credentials, if any, have to be handed to cache_peer separately rather
    # than left in the peer address.
    case "$hostport" in
        *@*) login=" login=${hostport%@*}" ;;
        *)   login="" ;;
    esac
    hostport=${hostport##*@}
    phost=${hostport%%:*}
    pport=${hostport##*:}
    [ "$pport" != "$phost" ] || pport=3128

    cat > "$PARENT_CONF" <<EOF
# Generated by squid.sh from \$HTTP_PROXY. Do not edit.
cache_peer $phost parent $pport 0 no-query default no-digest$login

# Local destinations must not be sent to the parent: the tests serve their own
# repositories and proxies from the host over the container bridge, and an
# external proxy cannot reach those.
acl kstest_local_dst dst 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 127.0.0.0/8
always_direct allow kstest_local_dst

# Everything else goes to the parent, with no direct fallback - falling back
# would reintroduce the hang this file exists to prevent.
never_direct allow all
EOF
    # Squid reads its configuration as root before dropping privileges, so 640
    # is readable by it. Only tighten when there is actually a secret in the
    # file, so the ordinary case stays easy to inspect.
    [ -z "$login" ] && chmod 644 "$PARENT_CONF" || chmod 640 "$PARENT_CONF"
    echo "Chaining squid to parent proxy $phost:$pport"
}

start() {
    if is_running; then
        echo "Already running"
        return 0
    fi

    # clean up stopped container from previous boot (usually one does not remember to call "squid.sh stop")
    $CRUN rm squid 2>/dev/null || true
    # This image is well-maintained (auto-built) and really small
    # However, we have to manually grab it and dump into our account because RH is limited by docker.io
    # docker.io/b4tman/squid -> quay.io/rhinstaller/squid
    if [ -n "$(proxy_url)" ]; then
        write_parent_conf
        parent_volume="--volume $PARENT_CONF:/etc/squid/conf.d.tail/parent.conf:ro,z"
    else
        parent_volume=""
    fi

    $CRUN run --net host --name squid --detach \
        --volume "$MYDIR"/squid-cache.conf:/etc/squid/conf.d.tail/cache.conf:ro,z \
        $parent_volume \
        --volume ks-squid-cache:/var/cache/squid quay.io/rhinstaller/squid

    # Redirect all traffic from external interfaces (like container bridges) through our local proxy
    # This does NOT re-route localhost traffic, as that does not go through PREROUTING.
    nft -f "$MYDIR"/squid-cache.nft

    if firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --add-port=3129/tcp
        # 3128 is squid's ordinary forward-proxy port, which the installer VMs
        # need when they cannot be served by transparent interception.
        firewall-cmd --add-port=3128/tcp
    fi

    announce_forward_proxy
}

# Transparent interception only catches plain http. Anything that ends up on
# https - which today includes dl.fedoraproject.org, as it redirects http to
# https - bypasses the cache entirely, and on a host without direct egress it
# does not merely miss the cache, it hangs. Pointing the installer at squid
# explicitly fixes both: http gets cached, https is tunnelled to the parent.
announce_forward_proxy() {
    gateway=$($CRUN network inspect podman --format '{{range .Subnets}}{{.Gateway}}{{end}}' 2>/dev/null) || gateway=""
    [ -n "$gateway" ] || return 0

    cat <<EOF

Squid is also reachable as an ordinary proxy at http://$gateway:3128
To send the installer's own downloads through it (and thus cache them), run
the tests with:

    KSTEST_EXTRA_BOOTOPTS=inst.proxy=http://$gateway:3128
EOF
}

stop() {
    if ! is_running; then
        echo "Already stopped"
        return 0
    fi

    nft delete table squid-cache

    $CRUN rm -f squid

    rm -f "$PARENT_CONF"

    if firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --remove-port=3129/tcp
        firewall-cmd --remove-port=3128/tcp
    fi
}

clean() {
    stop
    # clean up in case it still exists, but is stopped
    $CRUN rm -f squid 2>/dev/null || true
    if $CRUN volume inspect ks-squid-cache >/dev/null 2>&1; then
        $CRUN volume rm ks-squid-cache
    fi
}

case "${1:-}" in
    start) start ;;
    stop) stop ;;
    clean) clean ;;
    *) echo "Usage: $0 start|stop|clean" >&2; exit 1 ;;
esac
