#!/bin/sh
# Start/stop a transparent squid proxy in a container. System podman containers will
# automatically use this to route plain http traffic through the cache, and thus
# greatly speed up the kickstart tests.
#
# This does NOT work with user podman containers, as they don't use a bridge, but slirp.
# Transparent content caching does NOT work with https in principle.
#
# If $HTTP_PROXY is set, squid chains to it instead of fetching directly, so this
# also works on hosts whose only egress is through a proxy. On such a host https
# is additionally intercepted and tunnelled to that proxy - see write_splice_conf.
#
# Call this with "clean" to  drop the persistent squid cache.

set -eu

SELF=$(realpath "$0")
MYDIR=$(dirname "$SELF")
CRUN=${CRUN:-$(which podman docker 2>/dev/null | head -n1)}
IMAGE=quay.io/rhinstaller/squid

# Label carrying the fingerprint of the configuration a running container was
# built from; see config_fingerprint.
CONFIG_LABEL=kstest.squid.config

# Generated, not checked in: they depend on the environment squid runs in.
PARENT_CONF=/run/kstest-squid-parent.conf
SPLICE_CONF=/run/kstest-squid-splice.conf
SPLICE_PEM=/run/kstest-squid-splice.pem
SPLICE_SSLDIR=/run/kstest-squid-ssl
LOG_CONF=/run/kstest-squid-log.conf

# Squid's own diagnostics. The image sends cache_log to /dev/null, so when squid
# refuses a connection - a peek that finds no SNI, a parent it will not talk to -
# the access log records that it happened and nothing records why. Set
# $KSTEST_SQUID_DEBUG to get them onto the container log: "1" for a useful
# default, or any debug_options value to pick sections yourself. Leave it unset
# otherwise, as the interesting sections are a firehose under load.
KSTEST_SQUID_DEBUG=${KSTEST_SQUID_DEBUG:-}

is_running() {
    [ -n "$($CRUN ps -q -f 'name=^squid$')" ]
}

# Everything that decides how the container is built, boiled down to one value
# so that start() can tell whether the squid already running is the squid it
# would create. This container outlives the job that started it - nothing tears
# it down between runs, and the runner's own cleanup only removes containers
# built from the test image - so without this check a squid started once keeps
# whatever configuration it had until the machine is rebooted, and a fixed
# script silently has no effect.
#
# The script itself is in here deliberately, not just the inputs it reads: it is
# what generates the configuration files, so changing it is as much a change of
# configuration as changing $HTTP_PROXY. That is the case that actually went
# wrong - a runner kept serving a pre-fix squid through several jobs after the
# fix had landed, with every request timing out and nothing to suggest why.
config_fingerprint() {
    {
        proxy_url
        echo "$KSTEST_SQUID_DEBUG"
        echo "$IMAGE"
        cat "$SELF" "$MYDIR"/squid-cache.conf
    } | sha256sum | cut -d' ' -f1
}

# Where hosts that only permit proxied egress (such as the OpenShift runners)
# advertise their proxy. Both spellings are in common use.
proxy_url() {
    echo "${HTTP_PROXY:-${http_proxy:-}}"
}

# Chain squid to the host's proxy when there is one. Without this, squid tries
# to reach mirrors directly; where direct egress is blocked those connections
# time out rather than being refused, so tests hang with no error instead of
# failing. Nothing is written when the host has no proxy, which keeps the
# normal unrestricted case exactly as it was.
write_parent_conf() {
    url=$(proxy_url)
    # http://[user:pass@]host[:port][/] -> host, port
    hostport=${url#*://}
    hostport=${hostport%%/*}
    # Credentials, if any, have to be handed to cache_peer separately rather
    # than left in the peer address.
    case "$hostport" in
        *@*) login=" login=${hostport%@*}" ;;
        *)   login="" ;;
    esac
    hostport=${hostport##*@}
    phost=${hostport%%:*}
    pport=${hostport##*:}
    [ "$pport" != "$phost" ] || pport=3128

    cat > "$PARENT_CONF" <<EOF
# Generated by squid.sh from \$HTTP_PROXY. Do not edit.
cache_peer $phost parent $pport 0 no-query default no-digest$login

# Local destinations must not be sent to the parent: the tests serve their own
# repositories and proxies from the host over the container bridge, and an
# external proxy cannot reach those.
acl kstest_local_dst dst 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 127.0.0.0/8
always_direct allow kstest_local_dst

# Everything else goes to the parent, with no direct fallback - falling back
# would reintroduce the hang this file exists to prevent.
never_direct allow all
EOF
    # Squid reads its configuration as root before dropping privileges, so 640
    # is readable by it. Only tighten when there is actually a secret in the
    # file, so the ordinary case stays easy to inspect.
    [ -z "$login" ] && chmod 644 "$PARENT_CONF" || chmod 640 "$PARENT_CONF"
    echo "Chaining squid to parent proxy $phost:$pport"
}

# Give https a way out on hosts that only permit proxied egress. Chaining to the
# parent (above) fixes plain http, because that is intercepted and so becomes
# squid's own request, but nothing intercepts 443: the installer opens a direct
# connection to the mirror, which such a host drops. Because the connection is
# dropped rather than refused it times out instead of failing, so those tests
# hang rather than reporting an error.
#
# The installer cannot be told to use the proxy - see the comment on
# announce_forward_proxy - so 443 is intercepted too and squid peeks at the
# ClientHello just far enough to read the SNI, then splices: from that point it
# is a plain CONNECT tunnel to the parent. Nothing is decrypted, the origin's own
# certificate reaches the client unchanged, and no CA has to be installed in the
# test systems. It also means none of this traffic is cached - splicing buys
# connectivity, not caching, and caching https would require breaking TLS.
#
# Squid insists on a cert= for an ssl-bump port and starts the certificate
# generator even when every connection is spliced, so a self-signed certificate
# and an initialised database have to exist. Neither is ever shown to a client.
write_splice_conf() {
    if ! command -v openssl >/dev/null; then
        echo "openssl is required to intercept https on a proxied host" >&2
        exit 1
    fi

    openssl req -new -newkey rsa:2048 -sha256 -days 3650 -nodes -x509 \
        -subj "/CN=kstest-squid-splice" -keyout "$SPLICE_PEM.key" \
        -out "$SPLICE_PEM.crt" 2>/dev/null
    cat "$SPLICE_PEM.crt" "$SPLICE_PEM.key" > "$SPLICE_PEM"
    rm -f "$SPLICE_PEM.crt" "$SPLICE_PEM.key"
    # World readable although it contains a private key: squid loads signing
    # certificates after dropping privileges, so the container's squid user has
    # to be able to read it, and 600 root:root makes it fail to start with "No
    # valid signing certificate". That is acceptable only because this key is
    # inert - every connection is spliced, so it signs nothing and is never sent
    # to a client. It exists to satisfy the cert= that squid demands.
    chmod 644 "$SPLICE_PEM"

    # The generator refuses to run against a database it did not create, and
    # squid dies on startup if its helpers cannot start. Recreated from scratch
    # every time: it holds no state worth keeping when nothing is generated.
    rm -rf "$SPLICE_SSLDIR"
    mkdir -p "$SPLICE_SSLDIR"
    $CRUN run --rm --user 0 --volume "$SPLICE_SSLDIR":/ssl:z "$IMAGE" \
        sh -c '/usr/lib/squid/security_file_certgen -c -s /ssl/db -M 4MB >/dev/null && chown -R squid:squid /ssl'

    cat > "$SPLICE_CONF" <<EOF
# Generated by squid.sh because \$HTTP_PROXY is set. Do not edit.
sslcrtd_program /usr/lib/squid/security_file_certgen -s /var/lib/squid/ssl/db -M 4MB
https_port 3130 intercept ssl-bump cert=/etc/squid/kstest-splice.pem

# Peek only at step 1, which is enough to learn the SNI and therefore which host
# to ask the parent for, then hand the connection over untouched.
acl kstest_step1 at_step SslBump1
ssl_bump peek kstest_step1
ssl_bump splice all
EOF
    chmod 644 "$SPLICE_CONF"
    echo "Intercepting https on 3130 and tunnelling it to the parent proxy"
}

# Replaces the image's own conf.d.tail/squid-log.conf, which is why this repeats
# the access log settings from it: only cache_log and debug_options are new.
# Both logs go to the container's stdout, so "podman logs squid" has the whole
# story in order.
write_log_conf() {
    case "$KSTEST_SQUID_DEBUG" in
        # 83 is peek/splice and 28 is the access checks, which together cover
        # why a connection was refused. Section 26 (tunnel) is deliberately not
        # here: it logs every 64k of every tunnel and buries everything else.
        1|yes|true) debug_opts="ALL,1 83,3 28,3" ;;
        *)          debug_opts="$KSTEST_SQUID_DEBUG" ;;
    esac

    cat > "$LOG_CONF" <<EOF
# Generated by squid.sh from \$KSTEST_SQUID_DEBUG. Do not edit.
logfile_rotate 0
cache_store_log none
access_log stdio:/proc/self/fd/1
cache_log stdio:/proc/self/fd/1
debug_options $debug_opts
EOF
}

start() {
    want=$(config_fingerprint)

    if is_running; then
        have=$($CRUN inspect squid --format "{{index .Config.Labels \"$CONFIG_LABEL\"}}" 2>/dev/null) || have=""
        if [ "$want" = "$have" ]; then
            echo "Already running"
            return 0
        fi
        # Unlabelled means it predates this check, so it is stale by definition.
        echo "Squid is running with a different configuration; recreating it"
        # Before anything is generated, because stop() removes the generated
        # files - and its nft cleanup has to happen before start() adds the
        # rules again, as nft -f appends to an existing table rather than
        # replacing it.
        stop
    fi

    # clean up stopped container from previous boot (usually one does not remember to call "squid.sh stop")
    $CRUN rm squid 2>/dev/null || true
    # This image is well-maintained (auto-built) and really small
    # However, we have to manually grab it and dump into our account because RH is limited by docker.io
    # docker.io/b4tman/squid -> quay.io/rhinstaller/squid
    if [ -n "$(proxy_url)" ]; then
        write_parent_conf
        write_splice_conf
        proxy_volumes="--volume $PARENT_CONF:/etc/squid/conf.d.tail/parent.conf:ro,z
                       --volume $SPLICE_CONF:/etc/squid/conf.d.tail/splice.conf:ro,z
                       --volume $SPLICE_PEM:/etc/squid/kstest-splice.pem:ro,z
                       --volume $SPLICE_SSLDIR:/var/lib/squid/ssl:z"
    else
        proxy_volumes=""
    fi

    if [ -n "$KSTEST_SQUID_DEBUG" ]; then
        write_log_conf
        log_volume="--volume $LOG_CONF:/etc/squid/conf.d.tail/squid-log.conf:ro,z"
        echo "Squid diagnostics enabled (\$KSTEST_SQUID_DEBUG=$KSTEST_SQUID_DEBUG)"
    else
        log_volume=""
    fi

    $CRUN run --net host --name squid --detach \
        --label "$CONFIG_LABEL=$want" \
        --volume "$MYDIR"/squid-cache.conf:/etc/squid/conf.d.tail/cache.conf:ro,z \
        $proxy_volumes $log_volume \
        --volume ks-squid-cache:/var/cache/squid "$IMAGE"

    # Redirect all traffic from external interfaces (like container bridges) through our local proxy
    # This does NOT re-route localhost traffic, as that does not go through PREROUTING.
    nft -f "$MYDIR"/squid-cache.nft

    # Only when there is somewhere to tunnel it to. Without a parent, intercepting
    # 443 would replace a connection that works with one that cannot go anywhere.
    if [ -n "$proxy_volumes" ]; then
        nft add rule ip squid-cache prerouting tcp dport 443 redirect to :3130
    fi

    if firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --add-port=3129/tcp
        # 3128 is squid's ordinary forward-proxy port, which the installer VMs
        # need when they cannot be served by transparent interception.
        firewall-cmd --add-port=3128/tcp
        [ -z "$proxy_volumes" ] || firewall-cmd --add-port=3130/tcp
    fi

    announce_forward_proxy
}

# Caching only catches plain http. Anything that ends up on https - which today
# includes dl.fedoraproject.org, as it redirects http to https - bypasses the
# cache, and on a proxied host would not even connect; write_splice_conf gets it
# out to the parent, but nothing can cache it.
#
# The obvious fix is to point the installer at squid with inst.proxy. Do not:
# anaconda has no notion of a proxy exception and applies one to every fetch it
# makes, including the kickstart at http://10.0.2.2:<port>/ks.cfg that the tests
# serve themselves. 10.0.2.2 is QEMU's user-mode alias for this container and
# means nothing to squid, so each of those fetches dies after a 60s connect
# timeout - which is most of the suite, as the *-httpks tests, updates images
# and inst.addrepo all use the same address.
announce_forward_proxy() {
    gateway=$($CRUN network inspect podman --format '{{range .Subnets}}{{.Gateway}}{{end}}' 2>/dev/null) || gateway=""
    [ -n "$gateway" ] || return 0

    cat <<EOF

Squid is also reachable as an ordinary proxy at http://$gateway:3128 for
clients that can be pointed at it selectively.

Do NOT pass this to the installer as inst.proxy: anaconda would also route the
tests' own http://10.0.2.2:<port>/ks.cfg through it, which squid cannot reach,
and those tests fail after a 60s timeout each.
EOF
}

# Tearing down is deliberately not conditional on the container running. A squid
# that failed to start leaves everything except the container behind, and the
# firewall rules are the part that matters: nft -f adds to an existing table
# rather than replacing it, so each subsequent start appended another copy of
# every rule. Removing what is already absent is not a failure here.
stop() {
    is_running || echo "Already stopped, removing anything left behind"

    nft delete table ip squid-cache 2>/dev/null || true

    $CRUN rm -f squid >/dev/null 2>&1 || true

    rm -f "$PARENT_CONF" "$SPLICE_CONF" "$SPLICE_PEM" "$LOG_CONF"
    rm -rf "$SPLICE_SSLDIR"

    if firewall-cmd --state >/dev/null 2>&1; then
        firewall-cmd --remove-port=3129/tcp 2>/dev/null || true
        firewall-cmd --remove-port=3128/tcp 2>/dev/null || true
        firewall-cmd --remove-port=3130/tcp 2>/dev/null || true
    fi
}

clean() {
    stop
    # clean up in case it still exists, but is stopped
    $CRUN rm -f squid 2>/dev/null || true
    if $CRUN volume inspect ks-squid-cache >/dev/null 2>&1; then
        $CRUN volume rm ks-squid-cache
    fi
}

case "${1:-}" in
    start) start ;;
    stop) stop ;;
    clean) clean ;;
    *) echo "Usage: $0 start|stop|clean" >&2; exit 1 ;;
esac
