#!/bin/sh

set -ex

KSTESTS_REPOSITORY=${KSTESTS_REPOSITORY:-https://github.com/rhinstaller/kickstart-tests}
KSTESTS_BRANCH=${KSTESTS_BRANCH:-master}
KSTESTS_DIR=${APP_ROOT}/kickstart-tests
KSTESTS_TEST=${KSTESTS_TEST:-}
KSTESTS_KEEP=${KSTESTS_KEEP:-1}

UPDATES_IMAGE=${UPDATES_IMAGE:-""}
BOOT_ISO=${BOOT_ISO:-boot.iso}
ISO_DIR=${APP_DATA}/images
LOGS_DIR=${APP_DATA}/logs

# user can bind-mount a local kickstart-tests dir to test that
if [ -d /kickstart-tests ]; then
    # copy it so that we can write our *.ks files, fragments/, and so on
    cp -r /kickstart-tests ${KSTESTS_DIR}
else
    # if not given, check out current git
    git clone ${KSTESTS_REPOSITORY} ${KSTESTS_DIR}
    git -C ${KSTESTS_DIR} checkout ${KSTESTS_BRANCH}
    git -C ${KSTESTS_DIR} remote -v
fi

# Prepare the configuration
UPDATES_IMAGE_ARG=""
if [ -n "${UPDATES_IMAGE}" ]; then
  UPDATES_IMAGE_ARG="-u ${UPDATES_IMAGE}"
fi

TESTTYPE_ARG=""
if [ -n "${TESTTYPE}" ]; then
    TESTTYPE_ARG="-t ${TESTTYPE}"
fi

SKIP_TESTTYPES_ARG=""
if [ -n "${SKIP_TESTTYPES}" ]; then
    SKIP_TESTTYPES_ARG="-s ${SKIP_TESTTYPES}"
fi

# work around virt-install TOCTOU race <https://github.com/virt-manager/virt-manager/pull/175>
mkdir -p ~/.cache/virt-manager/boot

# Run the test
pushd ${KSTESTS_DIR}
RC=0
scripts/run_kickstart_tests.sh -k ${KSTESTS_KEEP} -i ${ISO_DIR}/${BOOT_ISO} ${UPDATES_IMAGE_ARG} ${TESTTYPE_ARG} ${SKIP_TESTTYPES_ARG} ${KSTESTS_TEST} || RC=$?
popd

# Copy logs to a volume
# Fixup permissions
chmod -R a+r /var/tmp/kstest-*
# Clean up (artifacts from broken test)
find /var/tmp/kstest-* -name "*.iso" -delete
find /var/tmp/kstest-* -name "*.img" -delete
# Move to target logs directory; this sometimes fails on nested directory permission/ownership
cp -r /var/tmp/kstest-* ${LOGS_DIR} || true

exit $RC
