#!/bin/sh
# Launch a scenario for the daily run.
set -eux

MYDIR=$(dirname $(realpath "$0"))
# tests often fail due to random infrastructure flakes; enable auto-retry
LAUNCH="$MYDIR/launch --retry"
ROOTDIR=$(dirname $(dirname "$MYDIR"))
SCENARIO="$1"
shift

case "$SCENARIO" in
    rawhide) $LAUNCH --skip-testtypes skip-on-fedora,knownfailure "$@" all ;;
    rawhide-text) $LAUNCH --skip-testtypes skip-on-fedora,knownfailure --run-args '-eKSTEST_EXTRA_BOOTOPTS=inst.text' "$@" all ;;
    daily-iso) $LAUNCH --skip-testtypes skip-on-fedora,knownfailure,rhbz1964819,rhbz1964817,rhbz1973156,rhbz1988344 --daily-iso="$GITHUB_TOKEN" "$@" all ;;

    rhel8)
        if [ ! -e data/images/boot.iso ]; then
            echo "INFO: data/images/boot.iso does not exist, downloading current RHEL 8 boot iso..."
            mkdir -p data/images
            curl -L http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/images/boot.iso --output data/images/boot.iso
        fi
        $LAUNCH --skip-testtypes skip-on-rhel,knownfailure,skip-on-rhel-8,rhbz1963834,rhbz1973156 --platform rhel8 --defaults "$ROOTDIR/scripts/defaults-rhel8.sh" all
        ;;

    rhel9)
        if [ ! -e data/images/boot.iso ]; then
            echo "INFO: data/images/boot.iso does not exist, downloading current RHEL 9 boot iso..."
            mkdir -p data/images
            curl -L http://download.eng.bos.redhat.com/rhel-9/development/RHEL-9-Beta/latest-RHEL-9/compose/BaseOS/x86_64/os/images/boot.iso --output data/images/boot.iso
        fi
        # FIXME: Temporarily disable the kdump addon in RHEL 9 (#1986942, #1986969).
        $LAUNCH --skip-testtypes skip-on-rhel,skip-on-rhel-9,knownfailure,rhbz1960279,rhbz1973156 --run-args '-eKSTEST_EXTRA_BOOTOPTS=inst.kdump_addon' --platform rhel9 --defaults "$ROOTDIR/scripts/defaults-rhel9.sh" all
        ;;

    # just run a single test on standard Rawhide; mostly for testing infrastructure
    minimal) $LAUNCH "$@" container ;;

    *) echo "ERROR: unknown scenario $1" >&2; exit 1 ;;
esac
