#!/bin/sh
# Launch a scenario for the daily run.
set -eux

LAUNCH=$(dirname "$0")/launch
SCENARIO="$1"
shift

case "$SCENARIO" in
    rawhide) $LAUNCH --skip-testtypes rhel-only,knownfailure "$@" all ;;
    rawhide-text) $LAUNCH --skip-testtypes rhel-only,knownfailure --run-args '-eKSTEST_EXTRA_BOOTOPTS=inst.text' "$@" all ;;
    daily-iso) $LAUNCH --skip-testtypes rhel-only,knownfailure --testtype packaging --daily-iso="$GITHUB_TOKEN" "$@" ;;
    # just run a single test on standard Rawhide; mostly for testing infrastructure
    minimal) $LAUNCH "$@" container ;;

    *) echo "ERROR: unknown scenario $1" >&2; exit 1 ;;
esac
