---
- hosts: kstest
  become: true
  become_user: root

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: rpm -q python2 > /dev/null || dnf -y install python2
      register: output
      changed_when: output.stdout != ""
    - name: Gathering facts
      setup:

  roles:
    - kstest
