#!/bin/bash

# Inventory for ansible was generated by linchpin based on PinFile layout configuration
INVENTORY=linchpin/inventories/kstest-controller.inventory

linchpin -v --workspace linchpin -p examples/controller-provisioning-linchpin/PinFile.controller -c linchpin/linchpin.conf destroy kstest-controller

rm ${INVENTORY}
