# Build Rawhide WebUI boot.iso daily (Anaconda COPR stack + inst.webui templates)
name: Build daily Rawhide+COPR WebUI boot.iso
on:
  schedule:
    - cron: 0 22 * * *
  # be able to start this action manually from a actions tab when needed
  workflow_dispatch:

jobs:
  boot_iso:
    uses: ./.github/workflows/daily-boot-iso-rawhide-reusable.yml
    with:
      webui: true
