# Doc: https://github.com/redhat-plumbers-in-action/differential-shellcheck#usage
---

name: Differential ShellCheck
on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        env:
          # -e SC2034: ignore because of TESTTYPE variable which is parsed out by
          #            tooling scripts as test case tags (gh#853)
          SHELLCHECK_OPTS: -e SC2034
        with:
          severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}
